/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PGR
 */
public class Panel extends javax.swing.JFrame {
    protected Hypothesis hyp;
    protected Function targetFunction;
    protected DataCollection data;
    protected int epochs;
    protected static double OFFSET = 50;
    protected static int MINX = -10;
    protected static int MAXX = 10;
    protected boolean isPaused;
    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        targetFunction = null;
        hyp = new Hypothesis(0.001);
        hyp.add(new Param(0,0));
        isPaused = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_console = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea_hypothesis = new javax.swing.JTextArea();
        label_alpha = new javax.swing.JLabel();
        label_error = new javax.swing.JLabel();
        label_hypothesis = new javax.swing.JLabel();
        label_epoch = new javax.swing.JLabel();
        label_epochDivider = new javax.swing.JLabel();
        btn_dataset = new javax.swing.JButton();
        btn_startPause = new javax.swing.JButton();
        btn_graph = new javax.swing.JButton();
        progressBar_cycle = new javax.swing.JProgressBar();
        progressBar_epoch = new javax.swing.JProgressBar();
        textField_alpha = new javax.swing.JTextField();
        textField_error = new javax.swing.JTextField();
        textField_epochs = new javax.swing.JTextField();
        textField_epochs_actual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textArea_console.setEditable(false);
        textArea_console.setColumns(20);
        textArea_console.setRows(5);
        jScrollPane1.setViewportView(textArea_console);

        textArea_hypothesis.setEditable(false);
        textArea_hypothesis.setColumns(20);
        textArea_hypothesis.setRows(5);
        jScrollPane2.setViewportView(textArea_hypothesis);

        label_alpha.setText("Alpha");

        label_error.setText("Error");

        label_hypothesis.setText("Hyp");

        label_epoch.setText("Epoch: ");

        label_epochDivider.setText("/");

        btn_dataset.setText("Add dataset");
        btn_dataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datasetActionPerformed(evt);
            }
        });

        btn_startPause.setText("Start");
        btn_startPause.setEnabled(false);
        btn_startPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startPauseActionPerformed(evt);
            }
        });

        btn_graph.setText("Graph");
        btn_graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graphActionPerformed(evt);
            }
        });

        textField_alpha.setEditable(false);
        textField_alpha.setText("0.000");

        textField_error.setEditable(false);
        textField_error.setText("0.0000");
        textField_error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_errorActionPerformed(evt);
            }
        });

        textField_epochs.setText("0");
        textField_epochs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_epochsActionPerformed(evt);
            }
        });

        textField_epochs_actual.setEditable(false);
        textField_epochs_actual.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressBar_epoch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(progressBar_cycle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_alpha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(textField_alpha, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_hypothesis)
                                    .addComponent(label_error))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField_error, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textField_epochs_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_epochDivider)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textField_epochs, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_epoch)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_dataset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_startPause)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_graph)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dataset)
                    .addComponent(btn_startPause)
                    .addComponent(btn_graph))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_alpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_alpha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_error, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_epoch)
                            .addComponent(textField_epochs_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_epochDivider)
                            .addComponent(textField_epochs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressBar_epoch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(progressBar_cycle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_hypothesis))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField_errorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_errorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_errorActionPerformed

    private void btn_datasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datasetActionPerformed
        // TODO add your handling code here:
        Panel_Function function = new Panel_Function(this, true);
        function.setVisible(true);
        this.btn_dataset.setEnabled(false);
        this.targetFunction = function.getFunction();
        this.textArea_console.setText("Function: " + targetFunction.toString());
        this.data = new DataCollection(this.targetFunction, MINX, MAXX, OFFSET);
        this.textArea_console.append(data.toString());
        this.btn_startPause.setEnabled(true);
    }//GEN-LAST:event_btn_datasetActionPerformed

    private void textField_epochsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_epochsActionPerformed
        // TODO add your handling code here:
        this.epochs = Integer.parseInt(textField_epochs.getText());
    }//GEN-LAST:event_textField_epochsActionPerformed

    private void btn_startPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startPauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_startPauseActionPerformed

    private void btn_graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graphActionPerformed
        // TODO add your handling code here:
        MatlabPanel matlabPanel = new MatlabPanel();
        matlabPanel.setVisible(true);
    }//GEN-LAST:event_btn_graphActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
                
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dataset;
    private javax.swing.JButton btn_graph;
    private javax.swing.JButton btn_startPause;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_alpha;
    private javax.swing.JLabel label_epoch;
    private javax.swing.JLabel label_epochDivider;
    private javax.swing.JLabel label_error;
    private javax.swing.JLabel label_hypothesis;
    private javax.swing.JProgressBar progressBar_cycle;
    private javax.swing.JProgressBar progressBar_epoch;
    private javax.swing.JTextArea textArea_console;
    private javax.swing.JTextArea textArea_hypothesis;
    private javax.swing.JTextField textField_alpha;
    private javax.swing.JTextField textField_epochs;
    private javax.swing.JTextField textField_epochs_actual;
    private javax.swing.JTextField textField_error;
    // End of variables declaration//GEN-END:variables
}
